apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels: 
    name: mongodb-pv
spec:
  capacity:
    storage: 256Mi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mongodb-pv
    fsType: ext4
    
