apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels: 
    name: mongodb-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db
#   gcePersistentDisk:
#     pdName: mongodb-pv
#     fsType: ext4
    
