apiVersion: v1
kind: Service
metadata:
  name: calculadora-service
spec:
  selector:
    app: calculadora-deployment
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
